name: Build Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Compile firmware
      run: |
        chmod +x compile-with-docker.sh
        ./compile-with-docker.sh sarteam

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v7
      with:
        name: sar-team-k5-k6-firmware
        path: compiled-firmware/f4hwn.sar-team.packed.bin
        if-no-files-found: error
